apiVersion: v1
kind: Secret
metadata:
    name: sops-smoketest
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rWl5zhCliiuQbwJUbogdGSuJlfDZpt4RPqe3vTdf+1kG8LGHs81ScYpSLtx5tilXmyq7yHyY2oKNQP1cP3/Y2WcJOVSu,iv:aU+gi5UTqeBO2Qgiaeh27apTJ+3GJS7BbHzNN6GArak=,tag:caUh2xeGLtO4sJgr0rFa0g==,type:comment]
    #ENC[AES256_GCM,data:UjdH6MnWIQu0A4paJ8JOfYwg5kUym7ZRf0+tUVW+k3OcFcs+bQwWAHjniqQ2Chd4uyM2cBJdJJ+/5LYt86S84LKyywJqLg==,iv:xqesEG6a3TNP1tS2aXYxsGX13zrIyd+epTTZOrdV1es=,tag:096btD7Mvkfve0kfVepEHw==,type:comment]
    #ENC[AES256_GCM,data:ih921qYZFrvgkTfhUkkAc8NPejb0hv5ns0CN2xVL6QfCB89RXDwypJM2fywgWZB8WU0HTsVGWY+zh2R+tojwSaiCMFI=,iv:3UjE8adfj8TvCN6PQ+m2J675IbWS9JZC+CU4xAeHQ4o=,tag:JwDjVczmOpViA0wL/v5AoA==,type:comment]
    #ENC[AES256_GCM,data:6PocmTqrVWn+kO6hjBDl5hx/PZCA8t4bMg==,iv:V1ouYFDPLS7lByJsV5jMetMnCrj9h6sJRhd6llDHi54=,tag:nLOuxY/rYV7ATLFKyNmf0w==,type:comment]
    message: ENC[AES256_GCM,data:TBw5o5Je7gYRC/K7mzXS,iv:8D2mQfEOSgLd9A7aFxMmCURiu+0udCD2IL9HFWiMThY=,tag:DJ67l4uCtShT8OKSVgyjDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzblFHbDY4eDBNdSsvZzZo
            YmsrMXd4Yml3YUlXWDJ6aHZUT1hoUktSSUVnCndyRVZ1VndMOWVOdU8rQmd5Wk9h
            SG1VcVphRERZbXYxQ1JuSkhxcjdIbVkKLS0tIGVXWW44ZDV6SXh0MnFyU0xUOEtC
            RlJNaDhNTFRJS1BnK1FpbGNsUW1yYzQK8qZ/Px5FsQHKPxQKogv28uxqC7lyK+pr
            1uzCYXXzyBYAltOtnO4ev1rph6XMwSn4Q5EDmvCFoG4Ln22ytlEymQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nd5tj64t0czmdk7ymjudav7pmk4p3wszpzd9vlnhpkh0cpx9ng9sn9d732
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T15:56:52Z"
    mac: ENC[AES256_GCM,data:UI3U1fAgNckW7wDdokfxmq3z1Fdt2J4KST/6PqAL/37kOLipjqQ9e/EGumLR0s1Akq7dA/Tg49Utsf2wvjewpX8xiVLc4G+aXQzDy7iQsrustWVObDwCNACA/+3GfMFQkjg3Y7jSqq9hPq5mGVO8OmgyOpJY146LI9JZGfZYGdA=,iv:i8bWww+tnnpNDKbk9dSNx832G/X36LKowJ/yucUPtuc=,tag:2PKaZW1quHI2aSnin76wjg==,type:str]
    version: 3.13.2
